//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEducation
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Please enter data!")]
        public string Title { get; set; }
        
        public string Sub_Title { get; set; }
        public string Sub_Title2 { get; set; }
        [StringLength(10,ErrorMessage ="Max 10 character!")]
        public string GNO { get; set; }
        public string Date { get; set; }
    }
}
